### PR TITLE
Markers

### PR DESCRIPTION
**Pull request by katalla1**
Markers added to map, pulled from the Db, currently using state, need to be refactored to redux

### CODE REVIEW

**Review by ryanji99 — CHANGES_REQUESTED** [review]
MapScreen.ts:
I see that you were once importing profileIcon from the constants folder but changed the import to ProfilePicture. That picture is then utilized for rendering markers on the map. Each marker can then be rendered with the setJobs function; great.

jobActions.ts
Great work on the modularized function. This is nice!

Requested Changes:
Currently, the jobActions.ts file shows `return data.jobs.jobs;`
Is this a typo? It seems redundant that you are accessing two nested fields with the same name. Pending @katalla1

**Comment by katalla1** [comment]
the collection of jobs returns an array of jobs, its just structured like that.

**Review by ryanji99 — APPROVED** [review]
You did not change anything but you claim it works. Pending @katalla1

**Review by ryanji99 — CHANGES_REQUESTED** [review]
Fix the nested jobs

**Comment by katalla1** [comment]
ok i will fix it 
its in the backend

**Comment by katalla1** [comment]
its fixed

**Review by ryanji99 — APPROVED** [review]
Approved

**Pull request merged**
