### PR TITLE
Refactored Types, Added Strict Typing For Navigation Routes & Props.

### PR DESCRIPTION
**Pull request by brianMxBm**

### CODE REVIEW

**Comment by ryanji99** [comment]
Pending review from @katalla1

**Review by ryanji99 — CHANGES_REQUESTED** [review]
Temporarily on hold. Broken navigation and route params. Will fix.

**Review by ryanji99 — DISMISSED** [review]
Types in Tabs.tsx are now working as intended

**Comment by ryanji99** [comment]
Pending @MxBM  and @katalla1 for review.

**Comment by brianMxBm** [comment]
Functions and looks good!

**Pull request merged**
